name: jonnie.io
baseurl: /blog
markdown: redcarpet
highlighter: pygments
exclude: [src, .editorconfig, .gitignore, CNAME, Gemfile, Gemfile.lock, README.md]

gems:
  - jekyll-redirect-from

whitelist:
  - jekyll-redirect-from
